using NPZ
using FileIO

function t_rewrite(t)
    t_new = zeros(Float64, size(t,1))
    for i in eachindex(t_new)
        t_new[i] = t[i]
    end
    return t_new
end


function u_rewrite(u) #Rewrites the 3D array of u from the JLD2 file into a 3D array that can be saved as a .npz file. The original u is a Vector of Vectors of Vectors, and this function converts it into a 3D Array of Float64.
    I = size(u,1)     #Guys this ^ description and the structure of this function was automatically generated by the suggestion AI. - Justin
    J = size(u[1],1)
    K = size(u[1][1],1)
    u_new = zeros(Float64, I, J, K)
    for i in 1:I
        for j in 1:J
            for k in 1:K
                u_new[i, j, k] = u[i][j][k]
            end
        end
    end
    return u_new
end

function mean_rewrite(mean) # also works for "var" since they have the same structure
    I = size(mean,1)
    J = size(mean[1],1)
    mean_new = zeros(Float64, I, J)
    for i in 1:I
        for j in 1:J
            mean_new[i, j] = mean[i][j]
        end
    end
    return mean_new
end

data_dir = "/home/justi/ME-598-Quadcopter/JustinWork/Julia/data/strong_15_85_2hz_clearance_planned/"
#save_dir = @__DIR__
#save_dir = save_dir * "/data/strong_wind_gust/"
save_dir = data_dir

nom_name = "states_nominal"
true_name = "states_true"
L1_name = "states_L1"

nom_states_jl = load(data_dir * nom_name * ".jld2");
true_states_jl = load(data_dir * true_name * ".jld2");
L1_states_jl = load(data_dir * L1_name * ".jld2");

#nom_states = Dict("t" => nom_states_jl["t"], "u" => u_rewrite(nom_states_jl["u"]), "mean" => nom_states_jl["mean"], "var" => nom_states_jl["var"]);
nom_states = Dict("t" => t_rewrite(nom_states_jl["t"]), "u" => u_rewrite(nom_states_jl["u"]), "mean" => mean_rewrite(nom_states_jl["mean"]), "var" => mean_rewrite(nom_states_jl["var"]))
true_states = Dict("t" => t_rewrite(true_states_jl["t"]), "u" => u_rewrite(true_states_jl["u"]), "mean" => mean_rewrite(true_states_jl["mean"]), "var" => mean_rewrite(true_states_jl["var"]))
L1_states = Dict("t" => t_rewrite(L1_states_jl["t"]), "u" => u_rewrite(L1_states_jl["u"]), "mean" => mean_rewrite(L1_states_jl["mean"]), "var" => mean_rewrite(L1_states_jl["var"]))


npzwrite(save_dir * nom_name * ".npz", nom_states)
npzwrite(save_dir * true_name * ".npz", true_states)
npzwrite(save_dir * L1_name * ".npz", L1_states)